import { Separator } from "@/components/ui/separator"
import Link from "next/link"

export default function TermsOfService() {
    return (
        <main className="flex items-center justify-center text-justify mt-10 mb-10">
            <div className="grid space-y-5 items-center justify-center w-full max-w-2xl">
                <h1 className="text-3xl font-semibold font-serif">Terms of Service</h1>
                <div>
                    <h2 className="font-semibold text-xl font-serif mb-2">Overview</h2>
                    <p>
                        BooklyAI provides a platform for generating eBooks using artificial intelligence.
                        These Terms apply to all visitors, users, and others who access the Services ("Users").
                    </p>
                </div>
                <Separator />
                <div>
                    <h2 className="font-semibold text-xl font-serif mb-2">Eligibility</h2>
                    <p>
                        You must be at least 18 years old to use our Services.
                        By using BooklyAI, you confirm that you meet this age requirement.
                    </p>
                </div>
                <Separator />
                <div>
                    <h2 className="font-semibold text-xl font-serif mb-2">Account Registration</h2>
                    <ol className="list-decimal list-inside space-y-4">
                        <li>
                            To access certain features of the Services, you may be required to create an account.
                        </li>
                        <li>
                            You are responsible for maintaining the confidentiality of your account credentials and are fully responsible for all activities that occur under your account.
                        </li>
                        <li>
                            You agree to provide accurate and complete information during the registration process and to update such information to keep it accurate and complete.
                        </li>
                    </ol>
                </div>
                <Separator />
                <div>
                    <h2 className="font-semibold text-xl font-serif mb-2">Use of Services</h2>
                    <ul className="list-disc list-inside space-y-4">
                        <li>
                            <strong>Permitted Use:</strong> You agree to use the Services only for lawful purposes and in accordance with these Terms.
                        </li>
                        <li>
                            <strong>Prohibited Use:</strong> You may not
                            <ol className="list-decimal list-inside ml-5 space-y-2">
                                <li>Use the Services to create content that violates copyright laws, contains hate speech, promotes illegal activities, or is otherwise harmful</li>
                                <li>Reverse engineer, decompile, or disassemble any portion of the Services.</li>
                                <li>Attempt to gain unauthorized access to any portion of the Services.</li>
                            </ol>
                        </li>
                    </ul>
                </div>
                <Separator />
                <div>
                    <h2 className="font-semibold text-xl font-serif mb-2">Content Ownership</h2>
                    <p>
                        Content generated by BooklyAI is provided to you under a license for personal or commercial use, subject to applicable laws and these Terms.
                    </p>
                </div>
                <Separator />
                <div>
                    <h2 className="font-semibold text-xl font-serif mb-2">Pricing and Payments</h2>
                    <ul className="list-disc list-inside space-y-4">
                        <li>
                            Access to certain features of the Services may require payment.
                            Prices are displayed on our website and are subject to change.
                        </li>
                        <li>
                            Payments are processed securely through third-party payment providers, such as LemonSqueezy.
                            By making a purchase, you agree to the terms of the respective payment provider.
                        </li>
                    </ul>
                </div>
                <Separator />
                <div>
                    <h2 className="font-semibold text-xl font-serif mb-2">Refund Policy</h2>
                    <p>Refunds are not available for any reason.</p>
                </div>
                <Separator />
                <div>
                    <h2 className="font-semibold text-xl font-serif mb-2">Privacy Policy</h2>
                    <p>
                        Our <Link href="/privacy-policy" className="text-medium underline">Privacy Policy</Link> explains how we collect, use, and protect your information.
                        By using the Services, you consent to the practices described in the Privacy Policy.
                    </p>
                </div>
                <Separator />
                <div>
                    <h2 className="font-semibold text-xl font-serif mb-2">Termination</h2>
                    <p>
                        We reserve the right to suspend or terminate your access to the Services at our sole discretion, without notice, if you violate these Terms or engage in any conduct that is harmful to BooklyAI or other Users.
                    </p>
                </div>
            </div>
        </main>
    )
}